### ISSUE TITLE
'RuntimeError: The data file data.dat does not exist' 

### ISSUE THREAD

**Issue by davidwjx** [euclidjda/deep-quant#1]
Thanks for good job in advance. 
I'm blocked on this issue when trying to 'python deep_quant.py'.  So, there's a sample or alternative of it for going further? 
If I have to construct it myself, with what format should I follow? Looking like benchmark-ew.dat?  Thank you.

**Comment by nachoaz** [comment]
Hi David, thanks for your interest. This is still very much a work in progress and at the moment we're not providing that .dat file. Please check again in a couple of weeks, though.

**Comment by davidwjx** [comment]
@nachoaz thanks for the response. Looking forward to your update.
