### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by shaunpwl** [euclidjda/deep-quant#10]
Thank you for making this available,

when i enter:  $ python build_data.py --N 10 --exclude_gics 40,45 --filename out.dat --test_mode yes
I get the error  "ImportError: No module named configparser"

I have installed configparser and am not sure why I am getting this error

**Comment by euclidjda** [comment]
There is not a script called build_data.py in the repo. There is: 

deep-quant/scripts/build_datfile.py

and

deep-quant/scripts/WRDS/build_data.py

Are you referring to one of those?

**Comment by shaunpwl** [comment]
yup I am referring to this one deep-quant/scripts/WRDS/build_data.py

**Comment by lakshaykc** [comment]
It should work if configparser is installed. What python version are you using? Are you using any virtual environment?

wrds module behaves differently if you're using a virtual environment.

**Comment by PallawiRajendra** [comment]
> yup I am referring to this one deep-quant/scripts/WRDS/build_data.py

Hi, There is a python file called build_data.py. This file should be there in the same folder where you are running your current code. That should solve the issue.
